from interfaces.card_model import Deck

cards: list[Deck] = [{
    "card_id": '1',
    "name": '1',
    'imageName': 'assets/cards/1.png',
    "text": 'card 1',
    "card_type": 'monster',
    'card_power': 3,
},
{
    "card_id": '2',
    "name": '2',
    'imageName': 'assets/cards/2.png',
    "text": 'card 2',
    "card_type": 'monster',
    'card_power': 4,
},
{
    "card_id": '3',
    "name": '3',
    'imageName': 'assets/cards/3.png',
    "text": 'card 3',
    "card_type": 'monster',
    'card_power': 3,
},
{
    "card_id": '4',
    "name": '4',
    'imageName': 'assets/cards/4.png',
    "text": 'card 4',
    "card_type": 'spell',
    'card_power': 3,
},
{
    "card_id": '5',
    "name": '5',
    'imageName': 'assets/cards/5.png',
    "text": 'card 5',
    "card_type": 'monster',
    'card_power': 4,
},
{
    "card_id": '6',
    "name": '6',
    'imageName': 'assets/cards/6.png',
    "text": 'card 6',
    "card_type": 'monster',
    'card_power': 2,
},
{
    "card_id": '7',
    "name": '7',
    'imageName': 'assets/cards/7.png',
    "text": 'card 7',
    "card_type": 'monster',
    'card_power': 3,
},
{
    "card_id": '8',
    "name": '8',
    'imageName': 'assets/cards/8.png',
    "text": 'card 8',
    "card_type": 'trap',
    'card_power': 1,
},
{
    "card_id": '9',
    "name": '9',
    'imageName': 'assets/cards/9.png',
    "text": 'card 9',
    "card_type": 'spell',
    'card_power': 3,
},
{
    "card_id": '10',
    "name": '10',
    'imageName': 'assets/cards/10.png',
    "text": 'card 10',
    "card_type": 'monster',
    'card_power': 6,
},
{
    "card_id": '11',
    "name": '11',
    'imageName': 'assets/cards/11.png',
    "text": 'card 11',
    "card_type": 'monster',
    'card_power': 3,
},
{
    "card_id": '12',
    "name": '12',
    'imageName': 'assets/cards/12.png',
    "text": 'card 12',
    "card_type": 'monster',
    'card_power': 5,
},
{
    "card_id": '13',
    "name": '13',
    'imageName': 'assets/cards/13.png',
    "text": 'card 13',
    "card_type": 'monster',
    'card_power': 3,
},
{
    "card_id": '14',
    "name": '14',
    'imageName': 'assets/cards/14.png',
    "text": 'card 14',
    "card_type": 'monster',
    'card_power': 6,
},
{
    "card_id": '15',
    "name": '15',
    'imageName': 'assets/cards/15.png',
    "text": 'card 15',
    "card_type": 'monster',
    'card_power': 3,
},
{
    "card_id": '16',
    "name": '16',
    'imageName': 'assets/cards/16.png',
    "text": 'card 16',
    "card_type": 'spell',
    'card_power': 3,
},
{
    "card_id": '17',
    "name": '17',
    'imageName': 'assets/cards/17.png',
    "text": 'card 17',
    "card_type": 'monster',
    'card_power': 1,
},
{
    "card_id": '18',
    "name": '18',
    'imageName': 'assets/cards/18.png',
    "text": 'card 18',
    "card_type": 'trap',
    'card_power': 1,
},
{
    "card_id": '19',
    "name": '19',
    'imageName': 'assets/cards/19.png',
    "text": 'card 19',
    "card_type": 'monster',
    'card_power': 2,
},{
    "card_id": '20',
    "name": '20',
    'imageName': 'assets/cards/20.png',
    "text": 'card 20',
    "card_type": 'monster',
    'card_power': 7,
}]