#     {
#     "onGameId": None,
#     "card_id": "4",
#     "card_name": "Pinguim feliz",
#     "card_image": "assets/cards/4.png",
#     "card_type": "monster",
#     "card_element": "cryo",
#     "card_attack": 15,
#     "card_def": 5,
#     "card_cust": 1,
#     "card_effect": None,
#     "card_description": "Nada além de um pinguim feliz, quem seria capaz de machucar essa carinha fofa?",
# },
#   {
#     "onGameId": None,
#     "card_id": "7",
#     "card_name": "Brokk, O ferreiro de Edênia",
#     "card_image": "assets/cards/7.png",
#     "card_type": "monster effect",
#     "card_element": "knight",
#     "card_attack": 20,
#     "card_def": 30,
#     "card_cust": 5,
#     "card_effect": None,
#     "card_description": "Efeito Reparável: aumenta em 10 a defesa de todos os aliados em campo. ",
# },
#     {
#     "onGameId": None,
#     "card_id": "8",
#     "card_name": "Heavy Castle",
#     "card_image": "assets/cards/8.png",
#     "card_type": "monster",
#     "card_element": "knight",
#     "card_attack": 60,
#     "card_def": 40,
#     "card_cust": 13,
#     "card_effect": None,
#     "card_description": "Castelo Motorizado Desenvolvido para defender o reino de Edênia de ameaças de alto nível. “Nunca subestime a precaução” ~ Brook",
# },
#     {
#     "onGameId": None,
#     "card_id": "12",
#     "card_name": "Espadapinguim",
#     "card_image": "assets/cards/12.png",
#     "card_type": "monster",
#     "card_element": "knight",
#     "card_attack": 10,
#     "card_def": 10,
#     "card_cust": 1,
#     "card_effect": None,
#     "card_description": "Empunhando a sua espada e escudo defende seu reino com fofura e muito orgulho.",
# },
#     {
#     "onGameId": None,
#     "card_id": "13",
#     "card_name": "Guarda real",
#     "card_image": "assets/cards/13.png",
#     "card_type": "monster",
#     "card_element": "knight",
#     "card_attack": 20,
#     "card_def": 10,
#     "card_cust": 2,
#     "card_effect": None,
#     "card_description": "Soldado honroso do castelo, empunha sua espada com orgulho para defender seu reino.",
# },
#     {
#     "onGameId": None,
#     "card_id": "24",
#     "card_name": "Pássaro brigão",
#     "card_image": "assets/cards/24.png",
#     "card_type": "monster",
#     "card_element": "anemo",
#     "card_attack": 15,
#     "card_def": 15,
#     "card_cust": 1,
#     "card_effect": None,
#     "card_description": "Ave irritada com garras sempre afiadas para a sua próxima luta.",
# },
#     {
#     "onGameId": None,
#     "card_id": "27",
#     "card_name": "Oog do Sul, O xãma da natureza",
#     "card_image": "assets/cards/27.png",
#     "card_type": "monster effect",
#     "card_element": "dendro",
#     "card_attack": 35,
#     "card_def": 25,
#     "card_cust": 6,
#     "card_effect": None,
#     "card_description": "Rejuvenescer:",
# },
#     {
#     "onGameId": None,
#     "card_id": "33",
#     "card_name": "Besta da floresta",
#     "card_image": "assets/cards/33.png",
#     "card_type": "monster",
#     "card_element": "dendro",
#     "card_attack": 35,
#     "card_def": 25,
#     "card_cust": 5,
#     "card_effect": None,
#     "card_description": "Uma fera de força incompreensível da natureza, protege a árvore da vida com força e ódio.",
# },
#     {
#     "onGameId": None,
#     "card_id": "54",
#     "card_name": "Infernal Regiscida",
#     "card_image": "assets/cards/54.png",
#     "card_type": "monster",
#     "card_element": "pyro",
#     "card_attack": 40,
#     "card_def": 25,
#     "card_cust": 7,
#     "card_effect": None,
#     "card_description": "Um antigo golem renascido das chamas.",
# },
#     {
#     "onGameId": None,
#     "card_id": "55",
#     "card_name": "Pyromance Rain",
#     "card_image": "assets/cards/55.png",
#     "card_type": "monster",
#     "card_element": "pyro",
#     "card_attack": 15,
#     "card_def": 15,
#     "card_cust": 2,
#     "card_effect": None,
#     "card_description": "Olha o céu mãe!, está caindo uma chuva de demônios de magma.",
# },
#     {
#     "onGameId": None,
#     "card_id": "56",
#     "card_name": "Oog do norte, O xãma do fogo",
#     "card_image": "assets/cards/56.png",
#     "card_type": "monster effect",
#     "card_element": "pyro",
#     "card_attack": 35,
#     "card_def": 25,
#     "card_cust": 7,
#     "card_effect": None,
#     "card_description": "Fúria: Quando invocado Oog invoca dois Pyromance Rain na arena.",
# },
